# input directory (path to project)
inputDir: src/test/resources/examples/cpp/realExamples2
# output directory
outputDir: output/train

# parse Python files with ANTLR parser
parser:
  name: fuzzy
  languages: [cpp]

filters:
  - name: by tree size  # exclude the trees that have > 1000 nodes
    maxTreeSize: 1000

# use file names as labels
# this selects the file level granularity
label:
  name: function name

# extract from each tree paths with length 9 and width 2
# save paths in code2vec format
storage:
  name: code2vec
  maxPathLength: 10
  maxPathWidth: 2
