<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.0 setup script
 * Date: Mon, 29 Mar 2021 04:55:48 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'qazwsx9980';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'V7)V<VTC9QP{O^D2"[)>G:]k;&^B1|O`';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>